### ISSUE TITLE
Can't install featureform==1.12.6

### ISSUE THREAD

**Issue by AlexanderDhoore** [featureform/featureform#1437]
### Expected Behavior

I'm trying to install featureform. I follow the quickstart, which says `pip install featureform`

https://docs.featureform.com/deployment/quickstart-docker

**This doesn't happen with featureform==1.12.5**

### Actual Behavior

Running `featureform` command gives:

```
Traceback (most recent call last):
  File "/usr/local/bin/featureform", line 5, in <module>
    from featureform.cli import cli
  File "/usr/local/lib/python3.12/site-packages/featureform/__init__.py", line 19, in <module>
    from .register import *
  File "/usr/local/lib/python3.12/site-packages/featureform/register.py", line 21, in <module>
    from .grpc_client import GrpcClient
  File "/usr/local/lib/python3.12/site-packages/featureform/grpc_client.py", line 8, in <module>
    from google.rpc import error_details_pb2, status_pb2
ModuleNotFoundError: No module named 'google.rpc'
```

### Steps To Reproduce

Here is a `Dockerfile` to reproduce it:

```
FROM python:3.10-slim
RUN pip install featureform==1.12.6
CMD featureform
```

Run `docker build . -t featureform && docker run featureform`

### What mode are you running Featureform in?

Local

### What version of Python are you running?

3.10

### Featureform Python Package Version

1.12.6

**Comment by AlexanderDhoore** [comment]
I gave up on the rest of the quickstart. This software feeels VERY beta.

```
~ $ featureform deploy docker --quickstart
Deploying Featureform on Docker
Starting Docker deployment on Linux 5.15.146.1-microsoft-standard-WSL2
Checking if featureform container exists...
Checking if quickstart-postgres container exists...
        Container quickstart-postgres not found. Creating new container...
        'quickstart-postgres' container started
Checking if quickstart-redis container exists...
        Container quickstart-redis not found. Creating new container...
        'quickstart-redis' container started

Pulling Quickstart files
        Pulling definitions.py

                    Failed to download https://featureform-demo-files.s3.amazonaws.com/definitions.py. Status code: 403

                    In order to download the file, you can get it directly from AWS.
                    ```
                    wget https://featureform-demo-files.s3.amazonaws.com/definitions.py -O quickstart/definitions.py
                    ```

                definitions.py could not be downloaded. Skipping...
        Pulling serving.py

                    Failed to download https://featureform-demo-files.s3.amazonaws.com/serving.py. Status code: 403

                    In order to download the file, you can get it directly from AWS.
                    ```
                    wget https://featureform-demo-files.s3.amazonaws.com/serving.py -O quickstart/serving.py
                    ```

                serving.py could not be downloaded. Skipping...
        Pulling training.py

                    Failed to download https://featureform-demo-files.s3.amazonaws.com/training.py. Status code: 403

                    In order to download the file, you can get it directly from AWS.
                    ```
                    wget https://featureform-demo-files.s3.amazonaws.com/training.py -O quickstart/training.py
                    ```

                training.py could not be downloaded. Skipping...

Featureform is now running!
To access the dashboard, visit http://localhost:80
Run jupyter notebook in the quickstart directory to get started.
~ $
~ $
~ $ docker ps -a
CONTAINER ID   IMAGE                               COMMAND                  CREATED              STATUS          PORTS                    NAMES
904503643f0c   redis:latest                        "docker-entrypoint.s…"   33 seconds ago       Up 31 seconds   0.0.0.0:6379->6379/tcp   quickstart-redis
9917fd0cf052   featureformcom/postgres             "docker-entrypoint.s…"   45 seconds ago       Up 42 seconds   0.0.0.0:5432->5432/tcp   quickstart-postgres
9a2603afd692   featureformcom/featureform:latest   "/usr/bin/supervisord"   About a minute ago   Created                                  featureform
~ $ export FEATUREFORM_HOST=localhost:7878
~ $
~ $ featureform apply quickstart/definitions.py --insecure
Traceback (most recent call last):
  File "/home/alexander/venv/bin/featureform", line 8, in <module>
    sys.exit(cli())
  File "/home/alexander/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/alexander/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/alexander/venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alexander/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alexander/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/alexander/venv/lib/python3.10/site-packages/featureform/cli.py", line 183, in apply
    raise ValueError(
ValueError: Argument must be a path to a file or URL with a valid schema (http:// or https://): quickstart/definitions.py
```

**Comment by AlexanderDhoore** [comment]
When I install featureform=1.12.5 the quickstart doesn't work on WSL ubuntu:

```
~ $ featureform deploy docker --quickstart
Deploying Featureform on Docker
Starting Docker deployment on Linux 5.15.146.1-microsoft-standard-WSL2
Checking if featureform container exists...
        Container featureform not found. Creating new container...
Traceback (most recent call last):
  File "/home/alexander/venv/lib/python3.10/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/home/alexander/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.43/containers/featureform/json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alexander/venv/lib/python3.10/site-packages/featureform/deploy.py", line 112, in start
    container = self._client.containers.get(config.name)
  File "/home/alexander/venv/lib/python3.10/site-packages/docker/models/containers.py", line 951, in get
    resp = self.client.api.inspect_container(container_id)
  File "/home/alexander/venv/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/alexander/venv/lib/python3.10/site-packages/docker/api/container.py", line 792, in inspect_container
    return self._result(
  File "/home/alexander/venv/lib/python3.10/site-packages/docker/api/client.py", line 271, in _result
    self._raise_for_status(response)
  File "/home/alexander/venv/lib/python3.10/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/home/alexander/venv/lib/python3.10/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.43/containers/featureform/json: Not Found ("No such container: featureform")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alexander/venv/lib/python3.10/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/home/alexander/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.43/containers/495ad07eb5e5945dbdec12adccaa977bba9ad9b7e3e17f31c766d61da4d3c6e8/start

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alexander/venv/bin/featureform", line 8, in <module>
    sys.exit(cli())
  File "/home/alexander/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/alexander/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/alexander/venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alexander/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alexander/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/alexander/venv/lib/python3.10/site-packages/featureform/cli.py", line 240, in deploy
    deployment_status = deployment.start()
  File "/home/alexander/venv/lib/python3.10/site-packages/featureform/deploy.py", line 127, in start
    container = self._client.containers.run(
  File "/home/alexander/venv/lib/python3.10/site-packages/docker/models/containers.py", line 880, in run
    container.start()
  File "/home/alexander/venv/lib/python3.10/site-packages/docker/models/containers.py", line 417, in start
    return self.client.api.start(self.id, **kwargs)
  File "/home/alexander/venv/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/alexander/venv/lib/python3.10/site-packages/docker/api/container.py", line 1135, in start
    self._raise_for_status(res)
  File "/home/alexander/venv/lib/python3.10/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/home/alexander/venv/lib/python3.10/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.43/containers/495ad07eb5e5945dbdec12adccaa977bba9ad9b7e3e17f31c766d61da4d3c6e8/start: Internal Server Error ("Ports are not available: exposing port TCP 0.0.0.0:80 -> 0.0.0.0:0: listen tcp 0.0.0.0:80: bind: Er is geprobeerd toegang te verkrijgen tot een socket op een volgens de toegangsmachtigingen niet toegestane manier.")
```

**Comment by AlexanderDhoore** [comment]
The main way to install your software has been broken for at least 2 weeks.

**Comment by swapdewalkar** [comment]
@AlexanderDhoore Try installing `googleapis-common-protos` or googleapis-common-protos[grpc]

**Comment by Atry** [comment]
Fixed in https://github.com/featureform/featureform/pull/1435
