### ISSUE TITLE
Can't search by vector using nearest neighbors

### ISSUE THREAD

**Issue by Matesanz** [featureform/featureform#251]
# Errror Description

When **trying to search by vector** an error is raised

```
neighbors = space.nearest_neighbors(vector=[0,0,1], num=2)
```

```python
Traceback (most recent call last):
  File "/workspace/main.py", line 31, in <module>
    neighbors = space.nearest_neighbors(vector=[0,0,1], num=10)
  File "/usr/local/lib/python3.9/site-packages/embeddinghub/client.py", line 154, in nearest_neighbors
    return self._client.nearest_neighbor(self._name, num, key=key, embedding=vector)
  File "/usr/local/lib/python3.9/site-packages/embeddinghub/client.py", line 365, in nearest_neighbor
    req = embedding_store_pb2.NearestNeighborRequest(space=str(space),
TypeError: Parameter to MergeFrom() must be instance of same class: expected featureform.embedding.proto.Embedding got list.
```

# How to replicate

Full code:

```python

import embeddinghub as eh

hub = eh.connect(eh.Config(host="embeddinghub", port=7462))  # we use docker
space = hub.create_space("quickstart", dims=3)

embeddings = {
    "apple": [1, 0, 0],
    "orange": [1, 1, 0],
    "potato": [0, 1, 0],
    "chicken": [-1, -1, 0],
}

space.multiset(embeddings)

neighbors = space.nearest_neighbors(vector=[0,0,1], num=2)  # << error here
print(neighbors)
```

**How can we convert a list or array into an Embedding?**.
Thank you in advance :smile:

**Comment by Atharva-Phatak** [comment]
Any updates on this ?? Can we use feature form to store huge embeddings, let's say, for some cases like Image embeddings?
