### ISSUE TITLE
[Bug]: Get and List commands in localmode print debugging message

### ISSUE THREAD

**Issue by sdreyer** [featureform/featureform#403]
### Expected Behavior

Running `featureform list`:
NAME                           VARIANT                        STATUS      

### Actual Behavior

Running `featureform list`:
Featureform Database exists. Connecting...
Featureform Database exists. Connecting...
NAME                           VARIANT                        STATUS                        
Featureform Database exists. Connecting...
Featureform Database exists. Connecting...

### Steps To Reproduce

Installing the featureform package and running `featureform list`:

### What mode are you running Featureform in?

Local

### What version of Python are you running?

3.7

### Featureform Python Package Version

1.1.10

### Featureform Helm Chart Version

NA

### Kubernetes Version

NA

**Comment by Sami1309** [comment]
Can't reproduce this.

Executing on 1.1.10 returns this error:
`Traceback (most recent call last):
  File "/home/sam/.local/bin/featureform", line 8, in <module>
    sys.exit(cli())
  File "/home/sam/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/sam/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/sam/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sam/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sam/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/sam/.local/lib/python3.10/site-packages/featureform/cli.py", line 141, in list
    rc_list_functions[resource_type]()
  File "/home/sam/.local/lib/python3.10/site-packages/featureform/register.py", line 1988, in list_labels
    return list_name_variant_status(self._stub, "label")
AttributeError: 'Client' object has no attribute '_stub'`
running `featureform list --local labels`

No error on latest pypackage
