### ISSUE TITLE
RuntimeError: The number of elements exceeds the specified limit

### ISSUE THREAD

**Issue by DerekChia** [featureform/featureform#89]
Hi, I read through the tutorial and was trying to load a trained embedding from fasttext using the `multiset` method but got into this error. A further search on this error seems to suggest that this is thrown by Hnswlib. I believe this has something to do with the `max_elements` that has to be initialised at the start. 

**Script**
```python
import io
import embeddinghub as eh

hub = eh.connect(eh.LocalConfig("data/"))

def load_vectors(fname):
    fin = io.open(fname, "r", encoding="utf-8", newline="\n", errors="ignore")
    n, d = map(int, fin.readline().split())
    data = {}
    for line in fin:
        tokens = line.rstrip().split(" ")
        data[tokens[0]] = tokens[1:]
    return data

embeddings = load_vectors("wiki-news-300d-1M.vec")

space = hub.create_space("quickstart", dims=300)

space.multiset(embeddings)

neighbors = space.nearest_neighbors(key="apple", num=2)
print(neighbors)
```

**Error**
```
Traceback (most recent call last):
  File "run.py", line 29, in <module>
    space.multiset(embeddings)
  File "/home/derek/anaconda3/envs/py38/lib/python3.8/site-packages/embeddinghub/client.py", line 91, in multiset
    self._idx.multiset(keyed_embeddings)
  File "/home/derek/anaconda3/envs/py38/lib/python3.8/site-packages/embeddinghub/offlinehub.py", line 97, in multiset
    self._idx.add_items(embeddings, idxs)
RuntimeError: The number of elements exceeds the specified limit
```

**Comment by chaituValKanO** [comment]
I am facing the same issue. Any fix or workaround for the same. I am loading around 80k vectors each of 768 dim.
