### ISSUE TITLE
[Bug]: Dashboard errors out with 500 server error

### ISSUE THREAD

**Issue by pbmiguel** [featureform/featureform#945]
### Expected Behavior

When following the [Quickstart (Docker)](https://docs.featureform.com/quickstart-docker), in step 5 when accessing the dashboard http://localhost:80 I expected to see an empty but working dashboard.

Notes:
- this error happens when using the `featureformcom/featureform:latest`
- this error does not occur when using the `featureformcom/featureform:0.8.9-rc`

### Actual Behavior

When accessing the dashboard http://localhost:80 it displays 500 Server Error.
The container logs of featureform report the following panic error:
```
{"level":"debug","msg":"Creating new metadata server"}
2023-08-04 15:28:58 {"level":"warn","ts":"2023-08-04T14:28:58.846Z","logger":"etcd-client","caller":"v3@v3.5.6/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0014c8e00/featureform-etcd:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing: dial tcp: lookup featureform-etcd on 192.168.65.7:53: no such host\""}
2023-08-04 15:28:58 {"level":"panic","msg":"Failed to create server","error":"could not configure storage provider: could not init etcd client: context deadline exceeded"}
2023-08-04 15:28:58 2023-08-04 14:28:58,846 INFO success: dashboard_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-04 15:28:58 panic: Failed to create server
```

### Steps To Reproduce

Execute the Docker deployment steps:
```
docker run -d -p 5432:5432 featureformcom/postgres
docker run -d -p 6379:6379 redis
docker run -p 7878:7878 -p 80:80 featureformcom/featureform
```

### What mode are you running Featureform in?

Local

### What version of Python are you running?

3.7

### Featureform Python Package Version

1.10

### Relevant log output

```shell
{"level":"info","msg":"Looking for metadata at: localhost:8080\n"}
2023-08-04 15:29:09 {"level":"debug","msg":"Creating new metadata server"}
2023-08-04 15:29:10 {"level":"warn","ts":"2023-08-04T14:29:10.503Z","logger":"etcd-client","caller":"v3@v3.5.6/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0015e0000/featureform-etcd:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing: dial tcp: lookup featureform-etcd on 192.168.65.7:53: no such host\""}
2023-08-04 15:29:10 {"level":"panic","msg":"Failed to create server","error":"could not configure storage provider: could not init etcd client: context deadline exceeded"}
2023-08-04 15:29:10 panic: Failed to create server
2023-08-04 15:29:10 
2023-08-04 15:29:10 goroutine 1 [running]:
2023-08-04 15:29:10 go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0xc00103fc58?, {0x0?, 0x0?, 0xc0016040a0?})
2023-08-04 15:29:10     /go/pkg/mod/go.uber.org/zap@v1.23.0/zapcore/entry.go:198 +0x65
2023-08-04 15:29:10 go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00160a1a0, {0xc00161a180, 0x1, 0x2})
2023-08-04 15:29:10     /go/pkg/mod/go.uber.org/zap@v1.23.0/zapcore/entry.go:264 +0x3ec
2023-08-04 15:29:10 go.uber.org/zap.(*SugaredLogger).log(0xc000b7eee8, 0x4, {0x38ed726?, 0x1c?}, {0x0?, 0x1?, 0x1?}, {0xc00103ff00, 0x2, 0x2})
2023-08-04 15:29:10     /go/pkg/mod/go.uber.org/zap@v1.23.0/sugar.go:287 +0xee
2023-08-04 15:29:10 go.uber.org/zap.(*SugaredLogger).Panicw(...)
2023-08-04 15:29:10     /go/pkg/mod/go.uber.org/zap@v1.23.0/sugar.go:227
2023-08-04 15:29:10 main.main()
2023-08-04 15:29:10     /app/metadata/dashboard/dashboard_metadata.go:1369 +0x773
2023-08-04 15:29:10 2023-08-04 14:29:10,511 INFO exited: dashboard_backend (exit status 2; not expected)
2023-08-04 15:29:11 2023-08-04 14:29:11,514 INFO spawned: 'dashboard_backend' with pid 207
2023-08-04 15:29:11 {"level":"info","msg":"Connecting to typesense at: http://localhost:7700\n"}
```

**Comment by anthonylasso** [comment]
Thanks for the report! We're looking at the issue.

**Comment by anthonylasso** [comment]
Quick update. We believe it's an issue with a recent change to `etcd`, so we're still looking at it.

**Comment by anthonylasso** [comment]
Testing the fix now, thank you all for your patience!
