### ISSUE TITLE
[Bug]: AttributeError: 'NoneType' object has no attribute 'StatusCode' in training.py from quickstart example

### ISSUE THREAD

**Issue by alexander-pv** [featureform/featureform#992]
### Expected Behavior

```
0 Features: [array([25.])] , Label: [False]
1 Features: [array([27999.])] , Label: [False]
2 Features: [array([459.])] , Label: [False]
3 Features: [array([2060.])] , Label: [True]
4 Features: [array([1762.5])] , Label: [False]
5 Features: [array([676.])] , Label: [True]
6 Features: [array([566.])] , Label: [True]
7 Features: [array([148.])] , Label: [True]
8 Features: [array([833.])] , Label: [True]
9 Features: [array([289.11])] , Label: [False]
10 Features: [array([259.])] , Label: [False]
11 Features: [array([202.])] , Label: [True]
```

### Actual Behavior

```
DeprecationWarning: pkg_resources is deprecated as an API
0 Features: [array([25.])] , Label: [False]
1 Features: [array([27999.])] , Label: [False]
2 Features: [array([459.])] , Label: [False]
3 Features: [array([2060.])] , Label: [True]
4 Features: [array([1762.5])] , Label: [False]
5 Features: [array([676.])] , Label: [True]
6 Features: [array([566.])] , Label: [True]
7 Features: [array([148.])] , Label: [True]
8 Features: [array([833.])] , Label: [True]
9 Features: [array([289.11])] , Label: [False]
10 Features: [array([259.])] , Label: [False]
11 Features: [array([202.])] , Label: [True]
Exception ignored in: <function _Rendezvous.__del__ at 0x7f2739dd3520>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/grpc/_channel.py", line 561, in __del__
AttributeError: 'NoneType' object has no attribute 'StatusCode'
```

### Steps To Reproduce

```python
from featureform import Client

client = Client(insecure=True)
dataset = client.training_set(name="fraud_training", variant="basic")

# Current error:
# AttributeError: 'NoneType' object has no attribute 'StatusCode'
for i, batch in enumerate(dataset):
    print(i, batch)
    if i > 10:
        break
```

### What mode are you running Featureform in?

Local, inside docker

### What version of Python are you running?

3.10

### Featureform Python Package Version

1.10.2

### Relevant log output

```shell
Exception ignored in: <function _Rendezvous.__del__ at 0x7f2739dd3520>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/grpc/_channel.py", line 561, in __del__
AttributeError: 'NoneType' object has no attribute 'StatusCode'
```
```

**Comment by sdreyer** [comment]
Hey @alexander-pv , thanks for bringing this up. We've looked into it and the data should be being returned as intended. However, it looks like the connection is closed improperly which is resulting in that error. We're working on getting a fix in for that.
